config/routes.rb
PlexusR3::Application.routes.draw do
  resources :users

  resources :projects do
    resources :comments, :nested_in => 'project'
    resources :images, :nested_in => 'project'
  end

  resources :samples do
    resources :comments, :nested_in => 'sample'
    resources :images, :nested_in => 'sample'
  end

  resources :data_nodes do
    resources :comments, :nested_in => 'data_node'
    resources :images, :nested_in => 'data_node'
    member do
      put :toggle
    end
  end

  resources :imports do
    collection do
      post :data_index
    end
  end

  resources :sessions

  root :to => 'projects#index'

  match 'login', :to => 'sessions#new'
  match 'logout', :to => 'sessions#destroy'

  match 'imports', :to => 'imports#create'
  match 'samples/stored_data', :to => 'imports#data_index'

  match 'pictures', :to => 'images#create'
end

app/models/sample.rb
class Sample < ActiveRecord::Base
  include Blame

  # t.string   "name"
  # t.string   "external_id"
  # t.datetime "created_at"
  # t.datetime "updated_at"

  # -- associations
  belongs_to :project
  has_many :comments, :as => :commentable, :dependent => :destroy
  has_many :images, :as => :illustratable, :dependent => :destroy
  has_many :data_nodes, :dependent => :destroy
  has_many :process_nodes, :dependent => :destroy
  has_many :imports, :dependent => :destroy

  # -- make sure sample names are unique (case-insensitive)
  validates :name, :presence => true, :uniqueness => { :scope => :project_id }
  validates :external_id, :presence => true,
                          :uniqueness => { :case_sensitive => false }

  # -- callbacks
  before_validation :generate_name

  # -- permissions are as in the project this sample belongs to
  def allows?(action, user)
    project && project.allows?(action, user)
  end

  # -- use a more permanent id to construct file system paths and such
  def id_for_assets
    external_id
  end

  # -- methods pertaining to the data relationships graph

  def data_nodes_by_id
    procs = process_nodes_by_id
    @nodes ||= Pazy::HashMap.new + data_nodes.map do |v|
      class << v; attr_accessor :sample, :producer end
      v.sample = self
      v.producer = procs[v.producer_id]
      [v.id, v]
    end
  end

  def process_nodes_by_id
    @procs ||= Pazy::HashMap.new + process_nodes.map { |v| [v.id, v] }
  end

  def graph
    @graph ||= data_nodes_by_id.values.inject(Pazy::DAG.new) do |gr, v|
      input_ids = v.producer ? v.producer.input_ids : []
      gr.with_vertex(v.id) + input_ids.map { |w_id| [w_id, v.id] }
    end
  end

  def bottlenecks
    @bottlenecks ||= graph.bottlenecks
  end

  # The list of valid and rejected node ids, with each node listed
  # before its successors.
  def nodes_sorted
    node_date = data_nodes_by_id.apply { |v| (v && v.date) || Time.at(0) }

    visit = proc do |state, v|
      if state.marked?(v)
        state
      else
        children = graph.succ(v).sort_by(&node_date).reverse
        children.inject(state.with_mark(v), &visit).after(v)
      end
    end

    sources = graph.sources.sort_by(&node_date).reverse
    sources.inject(Pazy::Accumulator.new, &visit)
  end
  
  # A list of node id/level pairs, selected and ordered as in
  # nodes_sorted, where the level of a node is one higher than the
  # maximum level of any of its predecessors.
  def nodes_with_levels
    level = nodes_sorted.inject(Pazy::HashMap.new) do |h, v|
      h.with(v, 1 + (graph.pred(v).map { |w| h[w] }.compact.max || -1))
    end

    nodes_sorted.map { |v| [v, level[v], bottlenecks.include?(v)] }
  end

  # -- other methods

  def stored_data()
    good_nodes = data_nodes.valid.reject do |node|
      node.filename.blank? and node.images.empty?
    end

    good_nodes.map do |node|
      sync_time = node.synchronized_at || Time.at(0)
      name = node.filename.blank? ? node.name : node.filename
      { "Name"       => name,
        "Identifier" => node.identifier,
        "IdInt"      => node.id,
        "IdExt"      => node.identifier,
        "Date"       => sync_time.getutc.strftime("%Y/%m/%d %H:%M:%S ") + 'UTC',
        "External"   => (not node.filename.blank?),
        "Images"     => node.images.map(&:filename)
      }
    end
  end

  def add_link(source, target)
    @graph = graph.with_edge(source.id, target.id)
    target.producer.add_input(source)
  end

  def destroy_node(v)
    @graph = graph.without_vertex(v.id)
    v.destroy
  end

  private
  
  def generate_name
    if self.external_id.blank?
      date = Date.today.strftime("%Y%m%d")
      last = self.class.where('external_id LIKE ?', "#{date}-%").
                        order(:external_id).last
      self.external_id = last ? last.external_id.succ : "#{date}-AA"
    end
  end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_authorization_filter :find_resource, :except => [:index, :new, :create]
  before_authorization_filter :find_project

  permit :index
  permit :new, :create, :destroy do may_edit(@project) end
  permit :show                   do may_view(@sample)  end
  permit :edit, :update          do may_edit(@sample)  end

  private

  def find_project
    @project = if @sample
                 @sample.project
               else
                 Project.where(:id => params[:project_id]).first
               end
  end

  public

  def index
    @samples = Sample.order(:name).select { |s| may_view(s) }
  end

  def show
  end

  def new
    @sample = @project.samples.build
  end

  def edit
  end

  def create
    if params[:result] == 'Cancel'
      flash[:notice] = 'Creation was cancelled.'
      redirect_to :action => :index
    else
      @sample = @project.samples.build(params[:sample])

      if @sample.save
        redirect_to @sample, :notice => 'Sample was successfully  created.'
      else
        render :action => 'new', :alert => 'Could not create sample.'
      end
    end
  end

  def update
    if params[:result] == 'Cancel'
      flash[:notice] = 'Update was cancelled.'
    elsif @sample.update_attributes(params[:sample])
      flash[:notice] = 'Sample was successfully updated.'
    else
      render :action => 'edit', :alert => 'Could not update sample.'
    end
  end

  def destroy
    @sample.destroy
    redirect_to @project, :notice => 'Sample successfully deleted.'
  end
end

app/views/samples/_form.html.haml
- project_id = @sample.project.id

= simple_form_for @sample do |form|
  - if create
    = form.input :name
  %br
  %input{ :type => 'hidden', :name => 'project_id', :value => "#{project_id}" }
  %br
  = form.submit 'Save', :name => 'result'
  = form.submit 'Cancel', :name => 'result'
  .clear

.clear

app/views/samples/_properties.html.haml
- @sample = properties

#properties.dj-anchor.dj-replace
  %h2
    Details:
    %span.action-links
      - if may_edit(@sample)
        %a.dj-link{ :href => edit_sample_url(@sample) }
          Edit
        = link_to "Delete", sample_url(@sample), |
                  :method => :delete, |
                  :confirm => "Destroy sample #{h @sample.name}?" |

  .properties
    %ul.dj-anchor
      %li
        %dfn Project
        = link_to @project.name, @project
      -#
        %li
          %dfn External ID
          = @sample.external_id
      .clear
  = timestamps(@sample)

app/views/samples/edit.html.haml
- title "Editing Sample <em>#{h @sample.name}</em>".html_safe

%fieldset#properties.dj-replace.dj-form.dj-anchor
  = render :partial => 'form', :locals => { :create => false }

app/views/samples/index.html.haml
- title 'Samples'

%table.zebra
  %thead
    %tr
      %th Sample
      -# %th External ID
      %th Data Nodes
  %tbody
    - @samples.select(&method(:may_view)).each do |sample|
      %tr{ :class => cycle('even', 'odd') }
        %td= link_to(sample.name, sample)
        -# %td= sample.external_id
        %td= sample.data_nodes.count

app/views/samples/new.html.haml
- title 'New Sample'

%fieldset= render :partial => 'form', :locals => { :create => true }

= link_to 'Back', @project

app/views/samples/show.html.haml
- title "Sample <em>#{h @sample.name}</em>".html_safe

= render :partial => "properties", :object => @sample
= render :partial => "images/on_object", :object => @sample
= render :partial => "comments/on_object", :object => @sample

%h2
  = @sample.data_nodes.empty? ? "No Datasets." : "Datasets:"
  - if may_edit(@sample)
    %span.action-links
      - if params[:showall]
        = link_to "Exclude hidden", url_for(:showall => nil)
      - else
        = link_to "Include hidden", url_for(:showall => 1)

- @sample.nodes_with_levels.each do |v, level, hideable|
  - node = @sample.data_nodes_by_id[v]
  - if !node.hidden or params[:showall]
    - graph = @sample.graph
    - locals = { :graph => graph, :level => level, :hideable => hideable }
    = render :partial => 'data_nodes/dataset', :locals => locals, :object => node

- if may_edit(@sample)
  %p
    %span#import-link.dj-replace.dj-anchor.action-links
      %a.dj-link{ :href => new_import_url(:sample_id => @sample.id) }
        Import data
  #import.dj-replace.dj-anchor

%h2 Imports:
%p= link_to 'Show Imports', imports_url(:sample_id => @sample.id)

app/views/samples/update.html.haml
- title "Sample <em>#{h @sample.name}</em>".html_safe

= render :partial => "properties", :object => @sample

= link_to "Full view", @sample