config/routes.rb
PlexusR3::Application.routes.draw do
  resources :users

  resources :projects do
    resources :comments, :nested_in => 'project'
    resources :images, :nested_in => 'project'
  end

  resources :samples do
    resources :comments, :nested_in => 'sample'
    resources :images, :nested_in => 'sample'
  end

  resources :data_nodes do
    resources :comments, :nested_in => 'data_node'
    resources :images, :nested_in => 'data_node'
    member do
      put :toggle
    end
  end

  resources :imports do
    collection do
      post :data_index
    end
  end

  resources :sessions

  root :to => 'projects#index'

  match 'login', :to => 'sessions#new'
  match 'logout', :to => 'sessions#destroy'

  match 'imports', :to => 'imports#create'
  match 'samples/stored_data', :to => 'imports#data_index'

  match 'pictures', :to => 'images#create'
end

app/models/user.rb
class User < ActiveRecord::Base
  # -- sets of abilities for certain roles
  READER_TASKS = [ 'login', 'view' ]
  EDITOR_TASKS = READER_TASKS + [ 'edit' ]
  ADMIN_TASKS  = EDITOR_TASKS + [ 'authorize', 'upload' ]
  WIZARD_TASKS = ADMIN_TASKS + [ 'impersonate' ]
  ABILITIES    = WIZARD_TASKS

  # -- fields
  include Blame

  # t.string   "login_name"
  # t.string   "hashed_password"
  # t.string   "first_name"
  # t.string   "last_name"
  # t.string   "email"
  # t.integer  "crypt_strength",  :default => 4
  # t.string   "organization"
  # t.string   "homepage"
  # t.string   "abilities",       :default => "login view"
  # t.datetime "created_at"
  # t.datetime "updated_at"

  # -- associations
  has_one  :activity_log
  has_many :memberships
  has_many :projects, :through => :memberships, :source => :project
  has_many :comments, :foreign_key => :author_id
  has_many :imports

  # -- these fields are used in forms but not stored
  attr_accessor :password, :password_confirmation

  # -- named scopes for selecting by role and for sorting
  scope :sorted, :order => [:last_name, :first_name]

  # -- the validations for this model
  validates :login_name,
    :uniqueness => { :case_sensitive => false },
    :format => {
      :with => /\A([a-z0-9.-]*)?\Z/i,
      :message => 'may only contain letters, digits, hyphens and dots'
    },
    :length => { :minimum => 3, :maximum => 40 },
    :presence => { :on => :create }

  validates :first_name, :presence => true
  validates :last_name, :presence => true
  
  validates :email, :presence => true, :format => {
    :with => /\A([A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4})?\Z/i,
    :message => 'does not look like an email address'
  }

  validates :homepage, :format => {
    :with => /\A(http:\/\/[A-Z0-9.-]+\.[A-Z]{2,4}(\/[A-Z0-9.-~]*)*)?\Z/i,
    :message => 'does not look like a URL'
  }

  validates :password, :presence => { :on => :create }
  validates :password_confirmation, :presence => { :on => :create }

  validates_each :password do |user, attr, value|
    if value.blank?
      user.errors[attr] << "can't be blank" if user.hashed_password.blank?
    elsif value.size < 6
      user.errors[attr] << "must have at least 6 characters"
    elsif value.size > 20
      user.errors[attr] << "may have at most 20 characters"
    elsif user.password_confirmation != value
      user.errors[:password_confirmation] << "does not match"
    end
  end

  # -- this produces the encrypted password for persistent storage
  before_save do |user|
    unless user.password.blank?
      user.hashed_password =
        Crypt::crypt(user.password, :strength => user.crypt_strength)
    end
  end

  # Make the abilities attribute look like an array
  def abilities
    (read_attribute(:abilities) || '').split(' ')
  end

  def abilities=(values)
    write_attribute(:abilities, (values || []).join(' '))
  end

  # Finds the user with the given login name and password, if any.
  def self.authenticate(params)
    login_name = params[:login_name] || params[:name]
    password = params[:password]
    user = self.where(:login_name => login_name).first
    user if user and Crypt::check(password, user.hashed_password,
                                  :strength => user.crypt_strength)
  end
  
  # The displayed name for this user.
  def name
    "#{first_name} #{last_name}"
  end
  
  # The name of the method that checks the given ability for a user.
  def self.ability_getter(a)
    "may_#{a}".to_sym
  end

  # The name of the method that adds or removes the given ability.
  def self.ability_setter(a)
    "may_#{a}=".to_sym
  end

  # -- define the getters and setters for all supported abilities
  ABILITIES.each do |a|
    define_method(ability_getter(a)) do
      abilities.include? a
    end

    define_method(ability_setter(a)) do |val|
      self.abilities = (val and val != '0') ? abilities | [a] : abilities - [a]
    end
  end

  # Checks whether the given user can perform the given action on this instance
  def allows?(action, user)
    case action.to_sym
    when :view then user.may_edit or user == self
    when :edit then user.may_authorize or user == self
    else            false
    end
  end

  # Checks whether this user can add or remove ability <a> for user <user>.
  def can_authorize?(user, a)
    user != self and may_authorize and
      (abilities | ADMIN_TASKS).include?(a)
  end

  # Logs an action (page view) for this user
  def log_activity(at, action = nil)
    unless activity_log
      update_attributes(:activity_log => ActivityLog.create(:user => self))
    end
    activity_log.add(at, action)
  end

  # Get the time of the last time the user was active
  def last_active
    activity_log && activity_log.last_time
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_authorization_filter :find_resource, :except => [:index, :new, :create]

  permit :index,        :if => :may_edit
  permit :new, :create  do may_authorize or bootstrapping? end
  permit :show          do may_view(@user) end
  permit :edit, :update do may_edit(@user) end

  redirect_if_cancelled


  def index
    @users = User.sorted.select { |u| may_view(u) }
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.login_name = params[:user][:login_name]
    @user.abilities = User::ADMIN_TASKS if bootstrapping?

    on_bootstraps = bootstrapping?
    if @user.save
      new_session(@user) if on_bootstraps
      redirect_to @user, :notice => 'User was successfully created.'
    else
      render :action => 'new', :alert => 'Could not create user.'
    end
  end

  def edit
  end

  def update
    User::ABILITIES.each do |a|
      unless can_authorize?(@user, a)
        params[:user].delete(User.ability_getter(a))
      end
    end
    if @user.update_attributes(params[:user])
      redirect_to @user, :notice => 'User was successfully updated.'
    else
      render :action => 'edit', :alert => 'Could not update user.'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= simple_form_for @user do |f|
  = f.input :login_name
  = f.input :first_name
  = f.input :last_name
  = f.input :organization
  = f.input :email
  = f.input :homepage
  = f.input :password
  = f.input :password_confirmation, :label => 'Confirm password'

  - User::ABILITIES.each do |a|
    - if can_authorize?(@user, a)
      = f.input User.ability_getter(a), :as => :boolean

  %br
  = f.submit 'Save', :name => 'result'
  = f.submit 'Cancel', :name => 'result'
  .clear
.clear

app/views/users/edit.html.haml
- title "Editing user <em>#{@user.login_name}</em>".html_safe

%fieldset= render :partial => 'form', :locals => { :create => false }

app/views/users/index.html.haml
- title 'Users'

%table.zebra
  %thead
    %tr
      %th User
      %th Name
      %th Email
      %th Organization
      %th Homepage
      %th Last active
  
  %tbody
    - @users.select(&method(:may_view)).each do |user|
      %tr{ :class => cycle('even', 'odd') }
        %td= link_to(user.login_name, user)
        %td= user.name
        %td= user.email
        %td= user.organization
        %td= user.homepage
        %td= user.last_active && format_time(user.last_active)

%br
= link_to('New user', new_user_path) if may_authorize

app/views/users/new.html.haml
- title 'New User'

%fieldset= render :partial => 'form', :locals => { :create => true }

app/views/users/show.html.haml
- title "User <em>#{h @user.login_name}</em>".html_safe

%h2
  Details:
  %span.action-links
    - if may_edit(@user)
      =link_to 'Edit', edit_user_url(@user)

.properties
  %ul
    %li
      %dfn Full name:
      = @user.name
    %li
      %dfn Email:
      = @user.email
    - unless @user.organization.blank?
      %li
        %dfn Organization:
        = @user.organization
    - unless @user.homepage.blank?
      %li
        %dfn Homepage:
        = @user.homepage
    %li
      %dfn Abilities:
      = (@user.abilities || []).join(', ')
    %li
      %dfn Last active:
      = @user.last_active && format_time(@user.last_active)
      .clear
= timestamps(@user)

%h2 Projects:
= @user.projects.map { |p| link_to(h(p.name), p) }.join(', ').html_safe