config/routes.rb
PlexusR3::Application.routes.draw do
  resources :users

  resources :projects do
    resources :comments, :nested_in => 'project'
    resources :images, :nested_in => 'project'
  end

  resources :samples do
    resources :comments, :nested_in => 'sample'
    resources :images, :nested_in => 'sample'
  end

  resources :data_nodes do
    resources :comments, :nested_in => 'data_node'
    resources :images, :nested_in => 'data_node'
    member do
      put :toggle
    end
  end

  resources :imports do
    collection do
      post :data_index
    end
  end

  resources :sessions

  root :to => 'projects#index'

  match 'login', :to => 'sessions#new'
  match 'logout', :to => 'sessions#destroy'

  match 'imports', :to => 'imports#create'
  match 'samples/stored_data', :to => 'imports#data_index'

  match 'pictures', :to => 'images#create'
end

app/models/project.rb
class Project < ActiveRecord::Base
  include Blame

  # t.string   "name"
  # t.string   "organization"
  # t.datetime "created_at"
  # t.datetime "updated_at"

  # -- associations
  has_many :samples, :dependent => :destroy
  has_many :memberships, :dependent => :destroy
  has_many :members, :through => :memberships, :source => :user
  has_many :comments, :as => :commentable, :dependent => :destroy
  has_many :images, :as => :illustratable, :dependent => :destroy

  # -- whitespace in the project name is normalized to single spaces
  before_validation do |project|
    project.name = project.name.strip.gsub(/\s+/, ' ')
  end

  # -- make sure project names are unique (case-insensitive)
  validates :name, :presence => true, :uniqueness => { :case_sensitive => false }

  # -- methods to inquire project memberships and user permissions
  def role_of(user)
    (m = membership_of(user)) && m.role
  end

  def allows?(action, user)
    role = role_of(user)
    case action.to_sym
    when :view
      user and user.may_view and not role.nil?
    when :edit
      user and user.may_edit and %w{contributor manager}.include? role
    when :manage
      user and user.may_edit and (user.may_authorize or role == 'manager')
    when :upload
      user and user.may_upload
    else
      false
    end
  end

  # -- use a more permanent id to construct file system paths and such
  def id_for_assets
    name
  end

  # -- pseudo-attribute for editing memberships and roles
  attr_accessor :_manager

  def roles
    User.sorted.map do |user|
      membership_of(user) ||
        Membership.new(:user => user,
                       :role => (user == _manager) ? 'manager' : '')
    end
  end

  def roles_attributes=(data)
    data.each { |key, value| set_role(User.find(value[:user_id]), value[:role]) }
  end

  # Assigns the given user the given role.
  def set_role(user, role)
    membership = membership_of(user)

    if membership
      if role.blank?
        membership.destroy
      else
        membership.update_attributes(:role => role)
      end
    elsif user and not role.blank?
      memberships.build(:user => user, :role => role)
    end
  end

  # -- private methods start here
  private

  def membership_of(user)
    user && memberships.where(:user_id => user.id).first
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_authorization_filter :find_resource, :except => [:index, :new, :create]

  permit :index
  permit :new, :create,           :if => :may_edit
  permit :show                    do may_view(@project)   end
  permit :edit, :update, :destroy do may_manage(@project) end

  helper_method :may_manage


  def index
    @projects = Project.order(:name).select { |p| may_view(p) }
  end

  def show
  end

  def new
    @project = Project.new
    @project._manager = current_user
  end

  def edit
  end

  def create
    if params[:result] == 'Cancel'
      flash[:notice] = 'Creation was cancelled.'
      redirect_to :action => :index
    else
      @project = Project.new(params[:project])
      @project.name = params[:project][:name]

      if @project.save
        redirect_to @project, :notice => 'Project was successfully  created.'
      else
        render :action => 'new', :alert => 'Could not create project.'
      end
    end
  end

  def update
    if params[:result] == 'Cancel'
      flash[:notice] = 'Update was cancelled.'
    elsif @project.update_attributes(params[:project])
      flash[:notice] = 'Project was successfully updated.'
    else
      render :action => 'edit', :alert => 'Could not update project.'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_url, :notice => 'Project successfully deleted.'
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= simple_form_for @project do |form|
  - if create
    = form.input :name
  = form.input :organization
 
  %p
    %label Members:
  %table
    %thead
      %tr
        %th User
        %th No Access
        %th Read Only
        %th Read/Write
        %th Manage
    %tbody
      = form.fields_for :roles do |role_fields|
        - user = role_fields.object.user
        %tr
          %td
            = role_fields.input :user_id, :as => :hidden
            = link_to user.name, user
          %td= role_fields.radio_button :role, '', :label => ''
          %td= role_fields.radio_button :role, 'client', :label => ''
          %td= role_fields.radio_button :role, 'contributor', :label => ''
          %td= role_fields.radio_button :role, 'manager', :label => ''

  %br
  = form.submit 'Save', :name => 'result'
  = form.submit 'Cancel', :name => 'result'
  .clear
.clear

app/views/projects/_properties.html.haml
- @project = properties

#properties.dj-anchor.dj-replace
  %h2
    Details:
    %span.action-links
      - if may_manage(@project)
        %a.dj-link{ :href => edit_project_url(@project) } Edit
        = link_to "Delete", project_url(@project), :method => :delete, |
                  :confirm => "Destroy project #{h @project.name}?" |

  .properties
    %ul.dj-anchor
      - unless @project.organization.blank?
        %li
          %dfn Organization
          = h(@project.organization)
      %li
        %dfn Members
        %ul
          - for user in @project.members
            %li
              = link_to user.name, user
              == (as #{@project.role_of(user)})
  = timestamps(@project)

app/views/projects/edit.html.haml
- title "Editing Project <em>#{h @project.name}</em>".html_safe

%fieldset#properties.dj-replace.dj-form.dj-anchor
  = render :partial => 'form', :locals => { :create => false }

app/views/projects/index.html.haml
- title 'Projects'

%table.zebra
  %thead
    %tr
      %th Project
      %th Organization
      %th Samples
  %tbody
    - @projects.select(&method(:may_view)).each do |project|
      %tr{ :class => cycle('even', 'odd') }
        %td= link_to(project.name, project)
        %td= project.organization
        %td= project.samples.count

%br
= link_to('New project', new_project_path) if may_edit

app/views/projects/new.html.haml
- title 'New Project'

%fieldset= render :partial => 'form', :locals => { :create => true }

= link_to 'Back', projects_path

app/views/projects/show.html.haml
- title "Project <em>#{h @project.name}</em>".html_safe

= render :partial => "properties", :object => @project
= render :partial => "images/on_object", :object => @project
= render :partial => "comments/on_object", :object => @project

%h2
  = if @project.samples.empty? then "No Sample." else "Samples:" end
  %span.action-links
    = link_to "Add one", new_sample_path(:project_id => @project.id)

%table.zebra
  %thead
    %tr
      %th Sample
      -# %th External ID
      %th Data Nodes
  %tbody
    - @project.samples.order(:name).each do |s|
      %tr
        %td= link_to s.name, s
        -# %td= s.external_id
        %td= s.data_nodes.count

app/views/projects/update.html.haml
- title "Project <em>#{h @project.name}</em>".html_safe

= render :partial => "properties", :object => @project

= link_to "Full view", @project