config/routes.rb
PlexusR3::Application.routes.draw do
  resources :users

  resources :projects do
    resources :comments, :nested_in => 'project'
    resources :images, :nested_in => 'project'
  end

  resources :samples do
    resources :comments, :nested_in => 'sample'
    resources :images, :nested_in => 'sample'
  end

  resources :data_nodes do
    resources :comments, :nested_in => 'data_node'
    resources :images, :nested_in => 'data_node'
    member do
      put :toggle
    end
  end

  resources :imports do
    collection do
      post :data_index
    end
  end

  resources :sessions

  root :to => 'projects#index'

  match 'login', :to => 'sessions#new'
  match 'logout', :to => 'sessions#destroy'

  match 'imports', :to => 'imports#create'
  match 'samples/stored_data', :to => 'imports#data_index'

  match 'pictures', :to => 'images#create'
end

app/helpers/layout_helper.rb
# These helper methods can be called in templates to set variables to be used in
# the layout.
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def strip_html(text)
    text.gsub(/<\/?[^>]*>/, "").gsub(/&[^;]*;/, "")
  end
end

app/views/layouts/application.html.haml
!!! Strict
%html{html_attrs}
  - stripped = request.xhr? || params[:stripped]

  %head
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    %title== Plexus - #{strip_html(yield(:title))}
    = csrf_meta_tag
    - unless stripped
      = stylesheet_link_tag 'application'
      = javascript_include_tag 'application'
      = yield(:head)
  %body
    #page
      - unless stripped
        #navigation
          %ul
            %li= link_to "Projects", projects_url
            %li= link_to "Users", users_url
            - if current_user
              %li= link_to "Logout", logout_url
            - else
              %li= link_to "Login", login_url
        #header
          = image_tag("grains-with-gradient.png", :alt => "")
          #logo
            = image_tag("logo-with-gradient.png", :alt => "PLEXUS")
        .clear
  
      #status-line
        #time-display== #{current_user && current_user.name} #{current_time}
        #notice.dj-replace.dj-anchor
          - if flash[:notice]
            %pre= flash[:notice]
            - flash[:notice] = nil
      .clear
  
      #content
        - if show_title? and not stripped
          %h1= yield(:title)
  
        #errors.dj-replace.dj-anchor
          - if flash[:alert] or flash[:error]
            #flash_alert
              %pre= flash[:alert]
              - flash[:alert] = nil
              %pre= flash[:error]
              - flash[:error] = nil
  
        #raw-content.dj-context= yield
      .clear

      - unless stripped
        #footer
          - if Rails.env.production?
            All rights reserved.
          - else
            Experimental Rails3 version.
        .clear